###  1. NEW NOTEBOOK CREATED

with the basic dependencies.

In [1]:
# import librabries
import pandas as pd
import numpy as np

print("Libraries imported!")

Libraries imported!

### 2. Scrap content from wiki page

In [2]:
# Use 'read_html' to scrapy the table
wiki_url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
wiki_tables = pd.read_html(wiki_url, header=0)
wiki_table1 = wiki_tables[0]

wiki_table1.head()

  Postal Code           Borough               Neighborhood
0         M1A      Not assigned                        NaN
1         M2A      Not assigned                        NaN
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

In [3]:
# The dataframe will consist of three columns: PostalCode, Borough, and Neighborhood
wiki_table1.rename(columns={'Postal Code':'PostalCode'}, inplace=True)

# Only process the cells that have an assigned borough. Ignore cells with a borough that is Not assigned.
wiki_table1.drop(wiki_table1[wiki_table1['Borough']=="Not assigned"].index, axis=0, inplace=True)
wiki_table1.head()

  PostalCode           Borough                                 Neighborhood
2        M3A        North York                                    Parkwoods
3        M4A        North York                             Victoria Village
4        M5A  Downtown Toronto                    Regent Park, Harbourfront
5        M6A        North York             Lawrence Manor, Lawrence Heights
6        M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [4]:
wiki_table = wiki_table1.reset_index()
wiki_table.drop(['index'], axis=1, inplace=True)
wiki_table

,PostalCode,Borough,Neighborhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [5]:
print("Shape: ", wiki_table.shape)

Shape:  (103, 3)

### Using the Geocoder package

In [7]:
geo_url = 'http://cocl.us/Geospatial_data'
coord = pd.read_csv(geo_url)
coord.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [8]:
toronto_df = pd.merge(wiki_table, coord, how='left', left_on = 'PostalCode', right_on = 'Postal Code')

# remove the "Postal Code" column
toronto_df.drop("Postal Code", axis=1, inplace=True)
toronto_df.head(12)

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
5,M9A,Etobicoke,"Islington Avenue, Humber Valley Village",43.667856,-79.532242
6,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
7,M3B,North York,Don Mills,43.745906,-79.352188
8,M4B,East York,"Parkview Hill, Woodbine Gardens",43.706397,-79.309937
9,M5B,Downtown Toronto,"Garden District, Ryerson",43.657162,-79.378937
10,M6B,North York,Glencairn,43.709577,-79.445073
11,M9B,Etobicoke,"West Deane Park, Princess Gardens, Martin Grov...",43.650943,-79.554724